cabledb/src/main/java/org/openepics/cable/ui/LoginController.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.ui;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.openepics.cable.services.SessionService;

import se.esss.ics.rbac.loginmodules.service.Message;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 5984791196886929176L;

    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());

    private static final String UNEXPECTED_ERROR = "Unexpected error";

    @Inject
    private SessionService sessionService;

    private String inputUsername;
    private String inputPassword;

    private boolean loginRequested;

    private void clearPassword() {
        inputPassword = null;
    }

    /** Initializes the bean for initial view display. */
    @PostConstruct
    public void init() {
        loginRequested = !sessionService.isLoggedIn();
    }

    /** Requests login. */
    public void requestLogin() {
        LOGGER.fine("Invoked request login.");
        loginRequested = true;
    }

    /** Performs login. */
    public void login() {
        LOGGER.fine("Invoked login.");
        try {
            final Message result = sessionService.login(inputUsername, inputPassword);
            if (result.isSuccessful())
                loginRequested = false;

            showMessage(result, "Sign In");
        } finally {
            clearPassword();
        }
    }

    /** Performs logout. */
    public void logout() {
        LOGGER.fine("Invoked logout.");
        try {
            final Message result = sessionService.logout();
            showMessage(result, "Sign Out");
        } finally {
            clearPassword();
        }
        loginRequested = true;
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(
                    FacesContext.getCurrentInstance().getExternalContext().getApplicationContextPath() +
                    FacesContext.getCurrentInstance().getViewRoot().getViewId());
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, UNEXPECTED_ERROR, e);
        }
        return;
    }

    /** Cancels login in progress. */
    public void cancel() {
        LOGGER.fine("Invoked cancel.");
        clearPassword();
        loginRequested = false;
    }

    /** @return the inputUsername */
    public String getInputUsername() {
        return inputUsername;
    }

    /**
     * @param inputUsername
     *            the inputUsername to set
     */
    public void setInputUsername(String inputUsername) {
        this.inputUsername = inputUsername;
    }

    /** @return the inputPassword */
    public String getInputPassword() {
        return inputPassword;
    }

    /**
     * @param inputPassword
     *            the inputPassword to set
     */
    public void setInputPassword(String inputPassword) {
        this.inputPassword = inputPassword;
    }

    /** @return the true if the login is currently requested, else false */
    public boolean isLoginRequested() {
        return loginRequested;
    }

    /** @return the true, if the login will be redirected to cable page */
    public boolean isCablesPage() {
        return "/cables.xhtml".equals(FacesContext.getCurrentInstance().getViewRoot().getViewId());
    }

    private void showMessage(Message result, String action) {

        final Severity severity = result.isSuccessful() ? FacesMessage.SEVERITY_INFO : FacesMessage.SEVERITY_ERROR;
        final String summary = action + " " + (result.isSuccessful() ? "Succeeded" : "Failed");
        final String message = result.getMessage();

        final FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(severity, summary, message));
    }
}

cabledb/src/main/java/org/openepics/cable/ui/MenuController.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package org.openepics.cable.ui;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

/**
 * A UI controller bean for the main menu.
 *
 * @author <a href="mailto:sunil.sah@cosylab.com">Sunil Sah</a>
 */
@ManagedBean
@ViewScoped
public class MenuController implements Serializable {

	private static final long serialVersionUID = -8204749848916147212L;

	public String getActiveIndex() {
        String viewId = FacesContext.getCurrentInstance().getViewRoot().getViewId();
        switch (viewId) {
            case "/cables.xhtml":
                return "0";
            case "/cable-types.xhtml":
                return "1";
            case "/routings.xhtml":
                return "2";
            case "/connectors.xhtml":
                return "3";
            case "/manufacturers.xhtml":
                return "4";
            case "/log.xhtml":
                return "5";
            default:
                return "0";
        }
    }
}

cabledb/src/main/webapp/WEB-INF/cableTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <f:facet name="first">
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
  </f:facet>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="resources/css/webfontkit/stylesheet.css" rel="stylesheet"
    type="text/css" />
  <link href="resources/css/default.css" rel="stylesheet"
    type="text/css" />
  <link href="resources/css/cssLayout.css" rel="stylesheet"
    type="text/css" />
  <title>#{msgs.title}</title>
  <h:outputScript library="js" name="cabledb-common.js" />
  <ui:insert name="head_content" />
</h:head>

<h:body>

  <p:dialog modal="true" widgetVar="statusDialog" showHeader="false"
    draggable="false" closable="false" resizable="false">
    <p:graphicImage value="/resources/images/ajax-loader.gif" />
  </p:dialog>

  <p:outputPanel id="full" layout="block">
  
	<div class="app_header">
	    <div class="logo">
            <h:outputText value="#{msgs.title}" styleClass="gui-title"/>
	    </div>
	    <div>
            <ui:include src="/WEB-INF/includes/tabmenu.xhtml" />
	    </div>
	    <div>
            <ui:include src="/WEB-INF/includes/dropmenu.xhtml" />
	    </div>
	</div>  

    <div style="padding: 15px 15px 0px 15px">
      <p:growl id="cableDBGrowl" showDetail="true" />
      <ui:insert name="content">Content</ui:insert>
    </div>

    <div class="footer-message">
        <h:outputText value="#{msgs.title} v#{msgs.titleVersion} - " />
        <h:outputLink rendered="#{UIPropertiesManager.supportEmail != null}"
                value="mailto:#{UIPropertiesManager.supportEmail}?subject=#{msgs.supportEmailSubject}"
                style="color: #A8A8A8;">
            Contact us
        </h:outputLink>
    </div>
  </p:outputPanel>

  <h:form id="loginForm">
    <p:dialog id="loginDialog" widgetVar="loginDialog" modal="true"
      visible="#{loginController.loginRequested}" closable="false">

      <f:facet name="header">
        <h:outputText value="Sign In" />
      </f:facet>
      <p:panelGrid id="grid" columns="2" styleClass="borderless">
        <h:outputLabel for="username" value="Username" />
        <h:panelGroup>
          <p:inputText id="username"
            value="#{loginController.inputUsername}" label="Username" />
          <p:watermark for="username" value="Enter username" />
          <p:message for="username" />
        </h:panelGroup>
        <h:outputLabel for="passwd" value="Password" />
        <h:panelGroup>
          <p:password id="passwd"
            value="#{loginController.inputPassword}" label="Password" />
          <p:watermark for="passwd" value="Enter password" />
          <p:message for="passwd" />
        </h:panelGroup>
      </p:panelGrid>
      <p:separator />

      <p:commandButton value="Sign In" update=":full :loginForm"
        action="#{loginController.login()}" style="float: left"
        onstart="start()" oncomplete="stop(); if (#{userManager.loggedIn}){remoteCommandLoad();};"
        rendered="#{loginController.cablesPage}" />

      <p:commandButton value="Sign In" update=":full :loginForm"
        action="#{loginController.login()}" style="float: left"
        onstart="start()" oncomplete="stop()"
        rendered="#{!loginController.cablesPage}" />

    </p:dialog>
  </h:form>

  <p:dialog modal="true" id="popupDialog" header="Warning"
    widgetVar="popupDialog"
    visible="#{applicationStateManager.namesServiceWarning}"
    closable="true">
    <div>The connection to the Naming Service could not be
      established.</div>
    <p:spacer width="32" />
    <p:commandButton value="Close" title="Close dialog."
      style="float:right" onclick="PF('popupDialog').hide();"
      icon="ui-icon-close" />
  </p:dialog>

  <script type="text/javascript">
            jQuery(window).resize(function() {
                adjustFooterPosition();
            });

            jQuery(document).ready(function() {
                adjustFooterPosition();
            });
        </script>

  <ui:include src="/resources/dialogs/error.xhtml" />
</h:body>

</html>

cabledb/src/main/webapp/WEB-INF/historyDataTable.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">
  <div style="width: calc(100% - 1em)">

    <p:remoteCommand name="updatePageSize" action="#{historyRequestManager.onPaginatePageSize}" />

    <p:dataTable id="historyTable" var="history"
      value="#{controller.lazyModel}" rowKey="#{history.id}"
      widgetVar="historyTable" class="dialogListTable"
      emptyMessage="No records found."
      scrollable="true"
      scrollWidth="100%"
      scrollHeight="#{tableHeight}"
      rows="#{controller.rows}"
      lazy="true"
      paginator="true"
      paginatorAlwaysVisible="true"
      paginatorPosition = "bottom"
      paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
      rowsPerPageTemplate="10,20,30,40,50">

      <p:ajax event="page" process="@this"
        listener="#{controller.onPaginate}"
        update="tableMenuActions"
        oncomplete="updatePageSize()" />
      <p:ajax event="filter" update="#{updateOnFilter}" />
      <p:ajax event="sort"
            onstart="start();"
            oncomplete="stop();" />

      <f:facet name="header">
        <p:commandButton id="toggler" type="button" value="Columns" style="float:left" />
        <p:columnToggler datasource="historyTable" trigger="toggler">
          <p:ajax event="toggle" listener="#{historyRequestManager.onToggle}" />
        </p:columnToggler>

        <p:menuButton id="tableMenuActions" value="Actions" style="float: right; text-align: left;">
          <p:menuitem
            id="exportLogButton" value="Export" onstart="start()"
            title="Export log" icon="ui-icon-disk" update=":dialogs"
            oncomplete="PF('exportDialog').show(); stop();"
            onclick="disableButtons('logTableForm','buttons');"  class = "button"
            disabled="#{historyRequestManager.history.size() == 0}" />

          <p:separator />
          <p:menuitem
            value="Close" title="Close history dialog." type="button"
            onclick="PF('#{widgetName}').hide();"
            action="#{controller.clearHistory()}" icon="ui-icon-close" />
         </p:menuButton>
      </f:facet>

      <p:column id="timestampColumn" sortBy="#{history.timestamp}"
        style="width:15%; min-width:100px"
        filterStyle="width:100%;"
        filterBy="#{history.timestamp}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(0)}">
        <f:facet name="header">
          <h:outputText value="Timestamp"
            title="History entry timestamp." />
        </f:facet>
        <h:outputText value="#{history.timestamp}" />
      </p:column>

      <p:column id="userColumn" sortBy="#{history.userId}"
        style="width:10%; min-width:100px"
        filterStyle="width:100%;"
        filterBy="#{history.userId}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(1)}">
        <f:facet name="header">
          <h:outputText value="User" title="User." />
        </f:facet>
        <h:outputText value="#{history.user}" />
      </p:column>

      <p:column id="entityType" sortBy="#{history.entityType}"
        style="width:10%; min-width:60px"
        filterStyle="width:100%;"
        filterBy="#{history.entityType}" filterMatchMode="exact"
        filterOptions="#{historyRequestManager.entityTypeValues}"
        visible="#{historyRequestManager.isColumnVisible(2)}"
        rendered="#{showType}">
        <f:facet name="header">
          <h:outputText value="Entity Type" title="Entity Type." />
        </f:facet>
        <h:outputText value="#{history.entityType}" />
      </p:column>

      <p:column id="operationColumn" sortBy="#{history.operation}"
        style="width:10%; min-width:60px"
        filterStyle="width:100%;"
        filterBy="#{history.operation}" filterMatchMode="exact"
        filterOptions="#{historyRequestManager.operationValues}"
        visible="#{historyRequestManager.isColumnVisible(3)}">
        <f:facet name="header">
          <h:outputText value="Operation" title="Operation." />
        </f:facet>
        <h:outputText value="#{history.operation}" />
      </p:column>

      <p:column id="entityNameColumn" sortBy="#{history.entityName}"
        style="width:20%; min-width:100px"
        filterStyle="width:100%;"
        filterBy="#{history.entityName}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(4)}">
        <f:facet name="header">
          <h:outputText value="Entity Name" title="Entity name." />
        </f:facet>
        <h:outputText value="#{history.entityName}" />
      </p:column>

      <p:column id="entityIdColumn" sortBy="#{history.entityId}"
        style="width:10%; min-width:60px"
        filterStyle="width:100%;"
        filterBy="#{history.entityId}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(5)}">
        <f:facet name="header">
          <h:outputText value="Entity ID" title="Entity ID." />
        </f:facet>
        <h:outputText value="#{history.entityId}" />
      </p:column>

      <p:column id="entryColumn" sortBy="#{history.entry}"
        style="width:25%; min-width:150"
        filterStyle="width:100%;"
        filterBy="#{history.entry}"
        filterMatchMode="contains"
        visible="#{historyRequestManager.isColumnVisible(6)}">
        <f:facet name="header">
          <h:outputText value="Change" title="Change description." />
        </f:facet>
        <p:commandLink update=":#{popupName}Form"
          oncomplete="PF('#{popupName}').show('#{component.clientId}');"
          styleClass="ellipsis">
          <f:setPropertyActionListener value="Change"
            target="#{historyRequestManager.longTextOverlayHeader}" />
          <f:setPropertyActionListener value="#{history.entry}"
            target="#{historyRequestManager.longTextOverlayContent}" />
          <h:outputText value="#{history.entry}" />
        </p:commandLink>
      </p:column>

    </p:dataTable>
  </div>
</ui:composition>

cabledb/src/main/webapp/WEB-INF/includes/dropmenu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui"
  xmlns:rc="http://java.sun.com/jsf/composite/comps"
  xmlns:h="http://java.sun.com/jsf/html">

  <h:form id="dropmenuform">

    <p:growl id="messages" showDetail="true" sticky="false" life="5000" />

    <p:menubar id="mainDropMenu">
      <p:submenu label="Templates" icon="ui-icon-calculator">
        <p:menuitem value="Cables" title="Download cables template"
          url="/resources/templates/cdb_cables.xlsx" />
        <p:menuitem value="Cable Types"
          title="Download cable types template"
          url="/resources/templates/cdb_cable_types.xlsx" />
        <p:menuitem value="Routings" title="Download routings template"
          url="/resources/templates/cdb_routings.xlsx" />
      </p:submenu>
      <p:submenu label="Help" icon="ui-icon-help">
        <p:menuitem value="User Manual" title="Download user manual"
          url="/resources/help/cable_database_user_manual.pdf"
          target="_blank" />
        <p:menuitem value="Cable Numbering"
          rendered="#{userManager.loggedIn}"
          url="#{cableRequestManager.cableNumberingSheetURL}"
          target="_blank" />
      </p:submenu>

      <f:facet name="options">
        <p:outputPanel id="refreshValidityPanel" layout="inline"
          style="font-size: smaller; font-style: italic;">
          <p:commandButton title="Refresh cable validity."
            icon="ui-icon-refresh" onstart="start();"
            oncomplete="stop(); location.reload();"
            actionListener="#{cableRequestManager.validateCables()}" />
        </p:outputPanel>
        <rc:logincomp ajax="false" />
      </f:facet>

    </p:menubar>
  </h:form>

</ui:composition>

cabledb/src/main/webapp/WEB-INF/includes/tabmenu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:p="http://primefaces.org/ui"
  xmlns:rc="http://java.sun.com/jsf/composite/comps"
  xmlns:h="http://java.sun.com/jsf/html">

  <h:form id="tabmenuform">

    <p:tabMenu id="mainTabMenu" activeIndex="${menuController.activeIndex}">
      <p:menuitem value="Cables" icon="ui-icon-home" url="cables.xhtml"
        styleClass="#{request.requestURI.contains('cables.xhtml') ? 'menu-selected' : ''}" />
      <p:menuitem value="Cable Types" icon="ui-icon-folder-open"
        url="cable-types.xhtml"
        styleClass="#{request.requestURI.contains('cable-types.xhtml') ? 'menu-selected' : ''}" />
      <p:menuitem value="Routings" icon="ui-icon-folder-open"
        url="routings.xhtml"
        styleClass="#{request.requestURI.contains('routings.xhtml') ? 'menu-selected' : ''}" />
      <p:menuitem value="Connectors" icon="ui-icon-folder-open"
        url="connectors.xhtml"
        styleClass="#{request.requestURI.contains('connectors.xhtml') ? 'menu-selected' : ''}" />
      <p:menuitem value="Manufacturers" icon="ui-icon-folder-open"
        url="manufacturers.xhtml"
        styleClass="#{request.requestURI.contains('manufacturers.xhtml') ? 'menu-selected' : ''}" />
      <p:menuitem value="Log" icon="ui-icon-folder-open" url="log.xhtml"
        styleClass="#{request.requestURI.contains('log.xhtml') ? 'menu-selected' : ''}" />
    </p:tabMenu>
  </h:form>

</ui:composition>

cabledb/src/main/webapp/expired.xhtml
<!DOCTYPE html>
<html lang="en">
<head>
<title>Session Expired</title>
</head>
<body>
  <h1>Session Expired</h1>
  <h3>You will be redirected to login page.</h3>
  <p>
    If the redirect does not work, click <a
      href="#{request.contextPath}/">here</a>.
  </p>
  
  <script type="text/javascript">
  // <![CDATA[
 function redirect(){
    window.location.href = '#{request.contextPath}/';
 }
 window.setTimeout(redirect, 3000);
// ]]>
</script>
</body>
</html>

cabledb/src/main/webapp/log.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
  template="/WEB-INF/cableTemplate.xhtml"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">

  <ui:define name="head_content">

    <h:form id="remoteCommandForm">
      <p:remoteCommand name="clearData"
        actionListener="#{historyRequestManager.clearHistory()}" />
    </h:form>

    <script type="text/javascript">
					clearData();
				</script>
  </ui:define>
  <ui:define name="content">
    <ui:fragment rendered="#{userManager.loggedIn}">
      <p:outputPanel id="dialogs">
        <p:growl id="messages" showDetail="true" sticky="false"
          life="5000" />

        <p:dialog id="exportDialog" header="Export Log" modal="true"
          widgetVar="exportDialog" visible="false" closable="false"
          dynamic="true">

          <h:form id="exportForm">

            <h:panelGroup rendered="true" layout="block">
              <div>
                Exporting
                <h:outputText
                  value="#{historyRequestManager.simpleTableExporter.entriesToExportSize}" />
                log entr
                <h:outputText
                  value="#{historyRequestManager.simpleTableExporter.entriesToExportSize == 1 ? 'y' : 'ies'}" />
                to Excel spreadsheet.
              </div>
            </h:panelGroup>
            <p:separator />

            <p:commandButton value="Export" title="Export log"
              style="float: left" ajax="false"
              update=":logTableForm:historyTable:tableMenuActions"
              onclick="PrimeFaces.monitorDownload(start, stop)">
              <p:fileDownload
                value="#{historyRequestManager.simpleTableExporter.exportedTable}" />
            </p:commandButton>

            <p:spacer width="32" />

            <div style="float: right">
              <p:commandButton value="Close" title="Close dialog."
                action="#{cableRequestManager.clearImportState()}"
                update=":dialogs :logTableForm:historyTable:tableMenuActions" />
            </div>
          </h:form>
        </p:dialog>
      </p:outputPanel>

      <h:form id="logTableForm">

        <ui:include src="/WEB-INF/historyDataTable.xhtml">
          <ui:param name="formId" value="logForm" />
          <ui:param name="widgetName" value="logDialog" />
          <ui:param name="title" value="Log" />
          <ui:param name="controller" value="#{historyRequestManager}" />
          <ui:param name="entity" value="entity" />
          <ui:param name="showType" value="true" />
          <ui:param name="updateOnFilter"
            value=":logTableForm:historyTable:tableMenuActions" />
          <ui:param name="tableHeight" value="calc(100vh - 18em)" />
          <ui:param name="popupName" value="displayLongTextPanel" />
        </ui:include>
      </h:form>

      <ui:include src="/resources/dialogs/display-long-general.xhtml">
        <ui:param name="formId" value="displayLongTextPanel" />
        <ui:param name="title"
          value="#{historyRequestManager.longTextOverlayHeader}" />
        <ui:param name="columnContent"
          value="#{historyRequestManager.longTextOverlayContent}" />
      </ui:include>

    </ui:fragment>
  </ui:define>
</ui:composition>

cabledb/src/main/webapp/resources/comps/logincomp.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:p="http://primefaces.org/ui"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:cc="http://java.sun.com/jsf/composite"
  xmlns:ui="http://java.sun.com/jsf/facelets">

<!-- INTERFACE -->
<cc:interface>
  <cc:attribute name="update" required="false" default="@all" />
  <cc:attribute name="ajax" required="false" default="true" />
</cc:interface>

<!-- IMPLEMENTATION -->
<!-- ToDo: Still not good. needs lots of improvements. too flaky  -->
<cc:implementation>
  <h:form id="_loginForm" rendered="#{userManager.loggedIn}">
    <p:growl id="_loginGrowl" showDetail="true" />
    <ui:remove> -------------------- Logout -------------------</ui:remove>
    <p:commandButton id="_loginOutButton" type="button"
      value="#{userManager.loggedInName}" icon="ui-icon-person"
      rendered="#{userManager.loggedIn}" />
    <p:overlayPanel id="_loginExitPanel" for="_loginOutButton"
      widgetVar="_loginExitWidget" style="border: 0px;"
      rendered="#{userManager.loggedIn}">
      <p:panelGrid styleClass="noBorders">
        <p:row>
          <p:column>
            <h:outputText
              value="You are logged in as #{userManager.loggedInName}" />
          </p:column>
        </p:row>
        <p:row>
          <p:column>
            <p:panelGrid styleClass="noBorders">
              <p:row>
                <p:column>
                  <p:commandButton value="Cancel" type="button"
                    onclick="PF('_loginExitWidget').hide()"
                    icon="ui-icon-cancel" />
                </p:column>
                <p:column>
                  <p:commandButton value="Logout"
                    update="@form #{cc.attrs.update}"
                    onstart="start();" oncomplete="stop();"
                    action="#{loginController.logout()}"
                    icon="ui-icon-power" />
                </p:column>
              </p:row>
            </p:panelGrid>
          </p:column>
        </p:row>
      </p:panelGrid>
    </p:overlayPanel>
  </h:form>
</cc:implementation>
</html>